name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select the base branch for release'
        required: true
      release_name:
        description: 'Enter the release name'
        required: true

jobs:
  create_release_branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      
      - name: Install SemVer
        run: npm install semver

      - name: Create release branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          git config user.name "Max Shymchuk"
          git config user.email "octorix@mail.ru"
          cd ${{ github.workspace }}
          git checkout ${{ inputs.branch }}
          current_version=$(node -p "require('./package.json').version")
          new_version=$(node -e "const semver = require('semver'); console.log(semver.inc('$current_version', 'major'))")
          git checkout -b release/${{ inputs.release_name }}
          npm version $new_version
          git commit -am "Release to $new_version"
          git push origin release/${{ inputs.release_name }}